package com.empresa.onboarding.state;

public enum StatusProposta {
    RASCUNHO,
    DADOS_PESSOAIS_ENVIADOS,
    DOCUMENTOS_PENDENTES,
    DOCUMENTOS_ENVIADOS,
    DOCUMENTOS_APROVADOS,
    DOCUMENTOS_REJEITADOS,
    EM_ANALISE_COMPLIANCE,
    ANALISE_COMPLIANCE_APROVADA,
    ANALISE_COMPLIANCE_REPROVADA,
    EM_ANALISE_RISCO,
    ANALISE_RISCO_APROVADA,
    ANALISE_RISCO_REPROVADA,
    AGUARDANDO_CONSENTIMENTO_OF,
    CONSENTIMENTO_OF_AUTORIZADO,
    CONSENTIMENTO_OF_REJEITADO,
    EM_ANALISE_INTEGRACAO_NUCLEO,
    INTEGRACAO_NUCLEO_APROVADA,
    INTEGRACAO_NUCLEO_REPROVADA,
    AGUARDANDO_CRIACAO_CONTA,
    CONTA_CRIADA,
    CONTA_ATIVADA,
    FINALIZADO,
    CANCELADO
}
